[package]
name = "bane_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.4.1"
chrono = "0.4.23"
clap = { version = "4.0.32", features = ["derive"] }
dashmap = "5.4.0"
futures = "0.3.25"
log = "0.4.17"
rand = "0.8.5"
serde_json = "1.0.93"
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "mysql", "chrono"] }
tokio = { version = "1.23.0", features = ["full"] }
warp = "0.3.3"
