services:
  mysql:
    image: mariadb
    command: mysqld --general-log=1
    volumes:
      - sql-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

volumes:
  sql-db:
