services:
  mysql:
    image: mysql
    volumes:
      - sql-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: name
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

volumes:
  sql-db:
