server_host = "::"
http_port = 8000
log_level = "DEBUG"
pub_dir = "pub_dir"
static_dir = "static"
scripts_path = "/tmp/scripts"
pub_file_prefix = "http://127.0.0.1:8000/"
arma_mission_dir = "./"
modpack_install_script = "./dummy-installer.nu"
steam_query_addr = "81.169.133.192:2303"
# steam_query_addr = "45.138.50.205:2303" # german thing
# steam_query_addr = "142.44.169.172:2303" # us thing
# steam_query_addr = "51.81.185.36:2303" # us thing
# steam_query_addr = "212.41.28.221:2303" # russian thing
