name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose --release
    - name: Store build artifact
      uses: actions/upload-artifact@v3
      with:
        name: bane_server
        path: target/release/bane_server
    - name: Cache Cargo packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          target
